#!/bin/sh

name="$(basename $0)"
eval env_dir=\$${name}DIR
dir="${inter:-$HOME/notes/}"

# this variable contains an optional suffix to remove from filenames
suffix=".txt"

# help text
help="$name, for carefree note taking and reading

You can change your notes directory by editing "\$dir" in $(which $0)
You can choose a file suffix to hide by editing "\$suffix" in $(which $0)

Usage:	$name				# print list of all notes
	$name <optional note> -w		# print path to notes or specific note
	$name <search string>		# if string is a note, open in editor
					# if not, search notes for string
	$name <note> -n			# open note in text editor
	$name -h OR -help OR --help		# print this help page
	Modes -n and -w can be placed before or after a note title.

Report any bugs to <lfamular@gmail.com>
"

edit_note() {
	${EDITOR:-vi} "$dir$1$suffix"
	return $?
}

ls_notes() {
	ls -rt $dir | strip_suffix
}

search_notes() {
	{ find -L $dir -iname "*$1*" | strip_prefix | strip_suffix ;
	grep -iso -E ".{0,30}$1.{0,30}" $dir* \
	| strip_prefix \
	| sed "s!$suffix:!\ :\ !" ; } \
	| nl | sort -nr | cut -f2- \
	| nl -n ln -s' ' -w2
}

strip_prefix() {
	while read input; do
		echo ${input#$dir}
	done
}

strip_suffix() {
	while read input; do
		echo ${input%$suffix}
	done
}

which_notes() {
	if [ -z "$1" ]; then
		printf "$dir\n"
	else
		test -e "$dir$1$suffix" || { printf "File not found: " 1>&2; ret=1; }
		printf "$dir$1$suffix\n"
	fi
	return ${ret:-0}
}

main() {
	[ -z "$1" ] && ls_notes

	while [ $# -gt 0 ]; do
		case "$1" in
		"-w" )
			wflag=1
			shift
			continue
			;;
		"-n" )
			nflag=1
			shift
			continue
			;;
		--help | -help | -h )
			hflag=1
			shift
			continue
			;;
		* )
			str="$1"
			shift
			continue
			;;
		esac
	done

	test ${nflag:-0} -eq 1 && { edit_note "$str"; ret=$?; bool="false"; }
	test ${wflag:-0} -eq 1 && { which_notes "$str"; ret=$?; bool="false"; }
	test ${hflag:-0} -eq 1 && { printf "$help"; bool="false"; }
	# this is basically testing twice...
	test ${bool:-true} = "true" && test -n "$str" && search_notes $str

	exit ${ret:-0}
}
main "$@"
