#!/bin/bash

_n() {

IFS=$'\n'
local cur
	cur=~/notes/${COMP_WORDS[COMP_CWORD]}
	COMPREPLY=( $( compgen -f $cur | cut -d / -f5 | sed 's/ /\ /g' | \
	sed 's/.txt$//' ) ) && compopt -o nospace
}
complete -o filenames -F _n n
