#! /bin/bash

# n, a note-taking script with Bash and Zsh completion.
# Copyright (C) 2013–2016 Leo Famulari <leo@famulari.name>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

_n() {

IFS=$'\n'
local cur notepath suffix

	# This variable contains the path to your notes
	notepath=~/notes/
	# This variable contains an optional suffix to hide from results
	suffix=".txt"

	cur=$notepath${COMP_WORDS[COMP_CWORD]}
	COMPREPLY=( $( compgen -f $cur | sed "s!$notepath!!" | sed 's/ /\ /g' | \
	sed "s/$suffix$//" ) ) && compopt -o nospace
}
complete -o filenames -F _n n
